In [38]:
import pandas as pd
import openpyxl

In [39]:
path = r"H:\Python\analise_dados\atividade 4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [40]:
bruto = pd.read_excel(path, header=2)

In [41]:
bruto

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
formatado = bruto.iloc[:5570, 1:]
formatado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [43]:
formatado.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022'],
      dtype='str')

In [44]:
formatado["diferença"] = formatado["População Censo 2022"] - formatado["População Município 2010\n(Sinopse)"]

In [45]:
porEstado = formatado.groupby("UF")[['População Município 2010\n(Sinopse)', 'População Censo 2022', "diferença"]].sum().reset_index()

In [46]:
porEstado

    UF  População Município 2010\n(Sinopse)  População Censo 2022  diferença
0   AC                             733559.0              830018.0    96459.0
1   AL                            3120494.0             3127683.0     7189.0
2   AM                            3483985.0             3941613.0   457628.0
3   AP                             669526.0              733759.0    64233.0
4   BA                           14016906.0            14141626.0   124720.0
5   CE                            8452381.0             8794957.0   342576.0
6   DF                            2570160.0             2817381.0   247221.0
7   ES                            3514952.0             3833712.0   318760.0
8   GO                            6003788.0             7056495.0  1052707.0
9   MA                            6574789.0             6776699.0   201910.0
10  MG                           19597330.0            20539989.0   942659.0
11  MS                            2449024.0             2757013.0   307989.0
12  MT                            3035122.0             3658649.0   623527.0
13  PA                            7581051.0             8120131.0   539080.0
14  PB                            3766528.0             3974687.0   208159.0
15  PE                            8796448.0             9058931.0   262483.0
16  PI                            3118360.0             3271199.0   152839.0
17  PR                           10444526.0            11444380.0   999854.0
18  RJ                           15989929.0            16055174.0    65245.0
19  RN                            3168027.0             3302729.0   134702.0
20  RO                            1562409.0             1581196.0    18787.0
21  RR                             450479.0              636707.0   186228.0
22  RS                           10693929.0            10882965.0   189036.0
23  SC                            6248436.0             7610361.0  1361925.0
24  SE                            2068017.0             2210004.0   141987.0
25  SP                           41262199.0            44411238.0  3149039.0
26  TO                            1383445.0             1511460.0   128015.0

In [47]:
porEstado = porEstado.sort_values(by="diferença", ascending=False)
porEstado = porEstado.reset_index(drop=True)
porEstado.to_csv(r"H:\Python\analise_dados\atividade 4/formatadoPorCrescimentoEstado.xlsx", sep =";")

In [48]:
porEstado

    UF  População Município 2010\n(Sinopse)  População Censo 2022  diferença
0   SP                           41262199.0            44411238.0  3149039.0
1   SC                            6248436.0             7610361.0  1361925.0
2   GO                            6003788.0             7056495.0  1052707.0
3   PR                           10444526.0            11444380.0   999854.0
4   MG                           19597330.0            20539989.0   942659.0
5   MT                            3035122.0             3658649.0   623527.0
6   PA                            7581051.0             8120131.0   539080.0
7   AM                            3483985.0             3941613.0   457628.0
8   CE                            8452381.0             8794957.0   342576.0
9   ES                            3514952.0             3833712.0   318760.0
10  MS                            2449024.0             2757013.0   307989.0
11  PE                            8796448.0             9058931.0   262483.0
12  DF                            2570160.0             2817381.0   247221.0
13  PB                            3766528.0             3974687.0   208159.0
14  MA                            6574789.0             6776699.0   201910.0
15  RS                           10693929.0            10882965.0   189036.0
16  RR                             450479.0              636707.0   186228.0
17  PI                            3118360.0             3271199.0   152839.0
18  SE                            2068017.0             2210004.0   141987.0
19  RN                            3168027.0             3302729.0   134702.0
20  TO                            1383445.0             1511460.0   128015.0
21  BA                           14016906.0            14141626.0   124720.0
22  AC                             733559.0              830018.0    96459.0
23  RJ                           15989929.0            16055174.0    65245.0
24  AP                             669526.0              733759.0    64233.0
25  RO                            1562409.0             1581196.0    18787.0
26  AL                            3120494.0             3127683.0     7189.0

In [49]:
porMunicipo = formatado.sort_values(by="diferença", ascending=False)
porMunicipo = porMunicipo.reset_index(drop=True)
porMunicipo.to_csv(r"H:\Python\analise_dados\atividade 4/formatadoPorCrescimentoMunicipio.xlsx", sep =";")

In [50]:
porMunicipo

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,AM,13.0,2603.0,Manaus,1802014.0,1802014.0,2063689.0,261675.0
1,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0
2,SP,35.0,50308.0,São Paulo,11253503.0,11253503.0,11451999.0,198496.0
3,SP,35.0,52205.0,Sorocaba,586625.0,586816.0,723682.0,137057.0
4,GO,52.0,8707.0,Goiânia,1302001.0,1301912.0,1437366.0,135365.0
...,...,...,...,...,...,...,...,...
5565,RS,43.0,14902.0,Porto Alegre,1409351.0,1409351.0,1332845.0,-76506.0
5566,PA,15.0,1402.0,Belém,1393399.0,1393399.0,1303403.0,-89996.0
5567,RJ,33.0,4904.0,São Gonçalo,999728.0,999728.0,896744.0,-102984.0
5568,RJ,33.0,4557.0,Rio de Janeiro,6320446.0,6320446.0,6211223.0,-109223.0
5569,BA,29.0,27408.0,Salvador,2675656.0,2675656.0,2417678.0,-257978.0